---
version: "2"
services:
  youtube-dl: 
    image: jeeaaasustest/youtube-dl
    container_name: youtube-dl
    volumes:
        - /homelab/docker/youtube-dl/downloads:/downloads
        - /homelab/docker/youtube-dl/data:/config
    ports: #default ports are 8080:8080 and 8081:8081
        - 8080:8080
        - 8081:8081  
    restart: unless-stopped
