---
services:
  adguardhome: #953 9784 9853 93000 9443
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 953:53/tcp
      - 953:53/udp
      - 9784:784/udp
      - 9853:853/tcp
      - 93000:3000/tcp
      - 980:80/tcp
      - 9443:443/tcp
    volumes:
      - /homelab/docker/adguardhome/workdir:/opt/adguardhome/work
      - /homelab/docker/adguardhome/confdir:/opt/adguardhome/conf
    restart: unless-stopped
