---
services:
  radarr: #7878
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /homelab/docker/radarr/data:/config
      - /homelab/docker/radarr/movies:/movies #optional
      - /homelab/docker/radarr/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
