---
services:
  swag: #443 & 80
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - URL=herkaraness.com
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    volumes:
      - /homelab/docker/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
