---
services:
  couchpotato: #5050
    image: lscr.io/linuxserver/couchpotato
    container_name: couchpotato
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /homelab/docker/couchpotato/config:/config
      - /homelab/docker/couchpotato/downloads:/downloads
      - /homelab/docker/couchpotato/movies:/movies
    ports:
      - 5050:5050
    restart: unless-stopped
